Algoritmo " crescente "

Var
    x, y: inteiro

Inicio

      escreval("digite dois numeros: ")
      leia(x, y)

      enquanto x<>y faca
       se x < y entao
         escreval("CRESCENTE!")
         escreval("digite outros dois numeros: ")
         leia(x, y)

       senao
          se x > y entao
           escreval("DECRESCENTE!")
           escreval("digite outros dois numeros: ")
           leia(x, y)


          fimse
       fimse
      fimenquanto















Fimalgoritmo
