Algoritmo "glicose "

Var
   medida: real

Inicio
      escreva("Digite a medida da glicose: ")
      leia(medida)

      se medida <= 100 entao
       escreva("Classificaçao: normal")
      senao
         se medida <= 140 entao
          escreva("Classificaçao: elevado")
         senao
            se medida > 140 entao
             escreva("Classificaçao: diabetes")
            fimse
          fimse
       fimse


















Fimalgoritmo